# Generated by Django 3.2 on 2021-05-01 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Book',
            new_name='book',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rank',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
